import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans, Merienda } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "@/components/ui/toaster";

const merienda = Merienda({
  subsets: ["latin"],
  variable: "--font-merienda",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "relative h-full bg-[radial-gradient(ellipse_at_center,var(--tw-gradient-stops))] from-black to-[#5d5d5d] font-sans antialiased",
            merienda.variable
          )}
        >
          <main className="relative flex flex-col min-h-screen">
            <div className="flex-grow flex-1">
              {children}
              <Toaster />
            </div>
            <Footer />
          </main>
        </body>
      </html>
    </QueryProvider>
  );
}
